### PR TITLE
Expose GpuMem in SurfacePlane

### PR DESCRIPTION
**Pull request by Yves33**
The pull request re-exposes GpuMem() in SurfacePlane. 
A unittest file is provided
Exposing GpuMem() avoids the overhead of using `__dlpack__` interface (usefull for opengl interop) and enables direct manipulation of SurfacePlanes through pycuda

### CODE REVIEW

**Comment by RomanArzumanyan** [comment]
Hi @Yves33 

Please fix your MR, it doesn't pass one of CI tests.

**Comment by Yves33** [comment]
The problem is not in the code but with my git knowledge and understanding, which is basically close to 0.
Trying to solve...

**Comment by Yves33** [comment]
any help on how to solve this git issue (I guess the problem comes from here)?
It seems that the change to PySurface.cpp is not taken into account.


```
Run actions/checkout@v3
Syncing repository: RomanArzumanyan/VALI
Getting Git version info
Temporarily overriding HOME='/media/vlabs/WD/actions-runner/_work/_temp/a0b933ca-f742-456d-8ad6-e49337feeffc' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /media/vlabs/WD/actions-runner/_work/VALI/VALI
/usr/bin/git config --local --get remote.origin.url
https://github.com/RomanArzumanyan/VALI
Removing previously created refs, to avoid conflicts
/usr/bin/git submodule status
 62100c123144ae7a80061f4220be2dbd3cbaefc7 extern/dlpack (v1.0rc)
Cleaning the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/56/merge
  Warning: you are leaving 1 commit behind, not connected to
  any of your branches:
  
    6cefe11 Merge ab62e8b07fe8a1ee66f4e2c23216eac166172334 into c52c4110de8163f7b1d2c5b7d0132d83bf40b890
  
  If you want to keep it by creating a new branch, this may be a good time
  to do so with:
  
   git branch <new-branch-name> 6cefe11
  
  HEAD is now at 5f5f7e2 Merge 0db2aad9a6c5b4fb5b4ef740f764bbb7148bb76b into c52c4110de8163f7b1d2c5b7d0132d83bf40b890
/usr/bin/git log -1 --format='%H'
'5f5f7e27ac21cae87cdddcd114ac3d90c72d53a4'
```

**Comment by RomanArzumanyan** [comment]
Hi @Yves33 

I'm looking into it now.
Not sure if issue lies on Git behalf or it's something with my self-hosted runner. Will come back as I find something.

**Comment by RomanArzumanyan** [comment]
Hi @Yves33 

Do you really want to mess with `pycuda` and memory copy code ?
IMO it's much easier to do something like this:

```python
import torch
import PyNvCodec as nvc
from parameterized import parameterized

@parameterized.expand([
    ["nv12", nvc.PixelFormat.NV12,],
    ["rgb", nvc.PixelFormat.RGB],
])
def test_gpu_mem(self, name, pix_fmt):
  surf = nvc.Surface.Make(format = pix_fmt, width = 640, height = 480, gpu_id = 0)
  tensor = torch.from_dlpack(surf)
  self.assertEqual(surf.GpuMem(), tensor.data_ptr)
```

Don't be afraid of introducing `torch` dependency - it's already there.

Also, please don't forget to do the following:

1. Bump the patch version bump in `setup.py` and `__init__.py` files.
2. Generate stubs in __init__`.pyi` interface file (new method shall be reflected there, otherwise Intellisense in IDEs wont highlight the `GpuMem` method).

**Comment by Yves33** [comment]
Hi @ roman

I agree that your code is much simpler. As far as I'm concerned, I don't *want* to mess with pycuda and memory copy code.  
I see 3 solutions for GpuMem unittest:
1 - checking through torch, as you just proposed:
\+ (pros) very simple unittest code. easier to maintain
\-  (cons) most python programs accessing GpuMem() maynot depend on Torch (otherwise they would use the __dlpack__ interface)
\- (cons) in my VALI development virtual env, I do not have Torch (but can install it)

2 - messing with pycuda
\+ (pros) reflects typical usage of GpuMem() and provides full working example (but maybe should move to /samples rather than /tests).  (VALI unit tests are written in a way to illustrate the API usage. One may follow them as samples.)
\+ (pros) no torch dependency.  
\- (cons)  pycuda dependency (new dependency for the project. I agree this is far from being optimal)
\- (cons) code is much heavier and harder to maintain, which is bad for unittest

3 - assessing whether GpuMem() returns same ptr as __dlpack__ embedded pointer
\+ (pros) minimal code (30 lines), easy to maintain
\+ (pros) no torch / pycuda dependancy (just dlpack, which is required for project compilation)
\- (cons) does not provide full example ot "typical" usage.
\- (cons) quite obscure code.
```python
import PyNvCodec as nvc
import unittest
from parameterized import parameterized

import ctypes, sys
sys.path.insert(0,"../extern/dlpack/apps/numpy_dlpack/dlpack")
from dlpack import _c_str_dltensor, DLManagedTensor

ctypes.pythonapi.PyCapsule_GetPointer.restype = ctypes.c_void_p
ctypes.pythonapi.PyCapsule_GetPointer.argtypes = [ctypes.py_object, ctypes.c_char_p]

pixel_formats=[[ k,v[0]] for k, v in nvc.PixelFormat.__entries.items() if k!='UNDEFINED' ]

def dlpackptr(plane:nvc.SurfacePlane):
    pycapsule=plane.__dlpack__()
    dl_managed_tensor = ctypes.pythonapi.PyCapsule_GetPointer(pycapsule, _c_str_dltensor)
    dl_managed_tensor_ptr = ctypes.cast(dl_managed_tensor, ctypes.POINTER(DLManagedTensor))
    return dl_managed_tensor_ptr.contents.dl_tensor.data

class TestGpuMem(unittest.TestCase):
    def __init__(self, methodName):
        super().__init__(methodName=methodName)

    '''@parameterized.expand([
        ["nv12", nvc.PixelFormat.NV12,],
        ["rgb", nvc.PixelFormat.RGB,],
    ])'''
    @ parameterized.expand(pixel_formats)
    def test_gpu_mem(self, name, pix_fmt):
        surf = nvc.Surface.Make(format = pix_fmt, width = 640, height = 480, gpu_id = 0)
        for idx in range(surf.NumPlanes()):
            self.assertEqual(surf.PlanePtr(idx).GpuMem(), dlpackptr(surf.PlanePtr(idx)))
    
if __name__ == "__main__":
    unittest.main()
```

Just tell me the option you prefer, and I'll rewrite the unittest in that direction.

**Comment by RomanArzumanyan** [comment]
Thank you for the clarification @Yves33, that's helpful.

> most python programs accessing GpuMem() maynot depend on Torch

Testing API with `torch` doesn't mean that **all** VALI users have to use it in their environment. As you may see in `setup.py` there are different sets of dependencies for different use cases and they all are **extras**. 

Tests rely `torch` just because it's handy, same as `unittest`, `pydantic` and `json`.

https://github.com/RomanArzumanyan/VALI/blob/541b74f5f55653eca3679f6976a535d9c090e6a2/setup.py#L28-L58

Those who are not interested in VALI development don't need these packages.

I'm following a simplest possible logic here: `GpuMem` basically returns an unsigned integer. If it has the same value as `torch.cuda_tensor.data_ptr` created from it (and memory content is the same which is easy to check if you download to numpy) - method returns "right" unsigned integer.

> in my VALI development virtual env, I do not have Torch (but can install it)

Please go ahead and do so. It's part of development and CI testing environment, and nothing more then that.

Just to make it clear: I'm OK with dlpack pointer comparison from your last code snippet, although I must agree the code looks busy and obscure. 

As a middle ground maybe it worth to develop a simpler sample which illustrate how to use `GpuMem` with pycuda (which doesnt cover multiple pixel formats) and keep the unit test as simple as possible ?

**Comment by Yves33** [comment]
OK. to summarize (just make sure we agree):
I'll rewrite a pull request with
+ comparison with dpack for unittest (solution 3)
+ sample basic pycuda usage
Do you prefer separates pull requests for sample and unittest?

**Comment by RomanArzumanyan** [comment]
@Yves33 

> Do you prefer separates pull requests for sample and unittest?

I'd prefer single PR. 

Looks like there's something going on with my self-hosted runner (that's the reason your PR doesn't pass tests) so I'll accept your PR in two steps:

- Merge it from your fork to feature branch in VALI repo
- Merge from feature branch to `main` in VALI repo. 

Better to do this once if possible.

Also, please don't forget to bump patch version and generate `__init__.pyi` file.

WRT to pycuda sample: if possible, please write it as Jupyter notebook. I found that many people find it more illustrative and easy to follow. Especially if there's some images to show, Jupyter simplifies that to a great extend.

**Comment by Yves33** [comment]
I'm afraid I need the right git commands to proceed as you expect...

> Looks like there's something going on with my self-hosted runner (that's the reason your PR doesn't pass tests) so I'll accept your PR in two steps:
> 
>     * Merge it from your fork to feature branch in VALI repo
> 
>     * Merge from feature branch to `main` in VALI repo
>

**Comment by RomanArzumanyan** [comment]
@Yves33 

> I'm afraid I need the right git commands to proceed as you expect...

That's on me, you don't need to change branches in your PR.

**Pull request closed without merging**
