### PR TITLE
PR #111

### PR DESCRIPTION
**Pull request by RomanArzumanyan**
This PR merges the changes from #111 to `main` branch.

### CODE REVIEW

**Comment by RomanArzumanyan** [comment]
@Yves33 @sandhawalia

PR #111 passes the tests, merging it into `main`.
It de-facto introduces the API breaking changes because `SeekMode.PREV_KEY_FRAME` no longer serves any purpose. So the minor version bump is done.

Thank you for your contribution !

**Comment by Yves33** [comment]
Hi,
thanks for merging!

SeekMode.PREV_KEY_FRAME can be used to stop on keyframes. In original PR the while loop in SeekDecode line ~873 had an early exit check which has disappeared in latest master
```
while (m_frame->pts + start_time < timestamp) {
      auto details = DecodeSingleFrame(dst);
      if (details.m_status != TaskExecStatus::TASK_EXEC_SUCCESS) {
        return details;
      }
     if (ctx.mode==PREV_KEY_FRAME){
          break;
      }
}
```
Is there a reason for this (or is it a mistake while editing PR)
It seems to me that some people might want to seek at stop at keyframes on keyframes.

**Comment by RomanArzumanyan** [comment]
Hi @Yves33 

It was causing seek sample to become useless. First decoded frame never changed and stayed the same as it was for frame 0.

**Comment by Yves33** [comment]
IMHO, removing `SeekMode mode;`  from SeekContext is unfortunate.

In sample_seek.ipynb (if that's the file you're refering to), the issue is just to pass the correct flag to mode
mode=vali.SeekMode.EXACT_FRAME (I suppose the mode flag was not initialized up to now, which corresponds to, vali.SeekMode.PREV_KEY_FRAME)
(PR_111 adjusted the flag in tests/test_PyDecoder.py, but forgot to change in samples/sample_seek.ipynb). 

*Don't want to struggle*, but it seems to me that it's unfortunate to lose the ability to seek to key frames (although I don't need it at the moment), as the amount of code to provide the feature is really minimal

by contrast, removing `int64_t out_frame_duration;int64_t num_frames_decoded;` from SeekContext is a good idea, as these fields are not updated.

**Pull request merged**
